[package]
name = "packt-gtk"
version = "0.1.0"
authors = ["frank"]

[dependencies]
relm = "0.14.4"
relm-derive = "0.14.4"
gtk = {version="0.4.1", features = ["v3_10"]}
packt-core = { path = "../packt-core" }

