unstable_features = true
reorder_impl_items = true
wrap_comments = true
format_strings = true
max_width = 80
merge_derives = false
use_field_init_shorthand = true
use_try_shorthand = true
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2