[package]
name = "packt-gui"
version = "0.1.0"
authors = ["frank"]

[dependencies]
relm = "^0.11.0"
relm-derive = "^0.11.0"
packt-core = { path = "../packt-core" }

[dependencies.gtk]
version = "^0.3.0"
features = ["v3_10"]